services:
  db:
    image: postgres:16
    container_name: memes-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: memes
      POSTGRES_PASSWORD: memes
      POSTGRES_DB: memesdb
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U memes -d memesdb"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 5s
    volumes:
      - memes_pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: src/Memes.Api/Dockerfile
    image: memes-api:latest
    container_name: memes-api
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__Default: Host=db;Port=5432;Database=memesdb;Username=memes;Password=memes;Include Error Detail=true
      Telegram__BotToken: 7483709546:AAFgSnIeT0miKTg6PXPmrOYAQ5-eB17XB8E
      Telegram__ChatId: "-1002961719948"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  memes_pgdata:
