name: Deploy API to EC2

on:
  push:
    branches: ["main"]
    paths:
      - "MemesService/**"
      - "scripts/deploy.sh"
      - ".github/workflows/deploy.yml"
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: Production #

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync repo to server
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }} # <-- REQUIRED
          REMOTE_HOST: ${{ secrets.SSH_HOST }} # <-- REQUIRED
          REMOTE_USER: ${{ secrets.SSH_USER }} # <-- REQUIRED
          REMOTE_PORT: ${{ secrets.SSH_PORT }} # optional (defaults to 22)
          SOURCE: "./"
          TARGET: "/srv/app"
          ARGS: "-rlptDz --delete"
          SSH_CMD_ARGS: "-o StrictHostKeyChecking=no"

      - name: Remote deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          envs: TARGET_DIR,ACME_EMAIL,API_DOMAIN,ASPNETCORE_ENVIRONMENT,POSTGRES_DB,POSTGRES_USER,POSTGRES_PASSWORD,REDDIT_CLIENT_ID,REDDIT_CLIENT_SECRET,REDDIT_USERNAME,REDDIT_PASSWORD,TELEGRAM_BOT_TOKEN,TELEGRAM_CHAT_ID
          script: |
            export TARGET_DIR="/srv/app/MemesService"
            export ACME_EMAIL="${{ secrets.ACME_EMAIL }}"
            export API_DOMAIN="${{ secrets.API_DOMAIN }}"
            export ASPNETCORE_ENVIRONMENT="Production"
            export POSTGRES_DB="${{ secrets.POSTGRES_DB }}"
            export POSTGRES_USER="${{ secrets.POSTGRES_USER }}"
            export POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}"
            export REDDIT_CLIENT_ID="${{ secrets.REDDIT_CLIENT_ID }}"
            export REDDIT_CLIENT_SECRET="${{ secrets.REDDIT_CLIENT_SECRET }}"
            export REDDIT_USERNAME="${{ secrets.REDDIT_USERNAME }}"
            export REDDIT_PASSWORD="${{ secrets.REDDIT_PASSWORD }}"
            export TELEGRAM_BOT_TOKEN="${{ secrets.TELEGRAM_BOT_TOKEN }}"
            export TELEGRAM_CHAT_ID="${{ secrets.TELEGRAM_CHAT_ID }}"
            bash /srv/app/scripts/deploy.sh
