name: Deploy API to EC2

on:
  push:
    branches: [ "main" ]
    paths:
      - "MemesService/**"
      - "scripts/deploy.sh"
      - ".github/workflows/deploy.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync repo to server
        uses: easingthemes/ssh-deploy@v5.0.3
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          ARGS: "-rlptDz --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          TARGET: "/srv/app"

      - name: Remote deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          envs: TARGET_DIR,ACME_EMAIL,API_DOMAIN,ASPNETCORE_ENVIRONMENT
          script: |
            export TARGET_DIR="/srv/app/MemesService"
            export ACME_EMAIL="${{ secrets.ACME_EMAIL }}"
            export API_DOMAIN="${{ secrets.API_DOMAIN }}"
            export ASPNETCORE_ENVIRONMENT="${{ secrets.ASPNETCORE_ENVIRONMENT }}"
            bash /srv/app/scripts/deploy.sh